
class World {
    constructor() {
        this.matrix = this.createWorld();
        this.tools = this.createTool();
    }
    createWorld() {
        let world = [
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Tree().leaf, new Tree().leaf, new Tree().leaf, new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Stone()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Tree().leaf, new Tree().leaf, new Tree().leaf, new Tree().leaf, new Tree().leaf, new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Stone(), new Stone(), new Stone()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Tree().leaf, new Tree().leaf, new Tree().leaf, new Tree().leaf, new Tree().leaf, new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Stone(), new Stone(), new Stone(), new Stone()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Tree().leaf, new Tree().leaf, new Tree().trunk, new Tree().leaf, new Tree().leaf, new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Tree().trunk, new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Tree().trunk, new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Tree().trunk, new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone()],
            [new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Tree().trunk, new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Sky(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone(), new Stone()],
            [new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass(), new Grass()],
            [new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground()],
            [new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground()],
            [new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground()],
            [new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground()],
            [new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground()],
            [new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground()],
            [new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground(), new Ground()],
        ];
        return world;
    }
    createTool() {
        let tools = [
            new Axe(), new Pickaxe(), new Shovel(), new Tool()
        ]
        return tools;
    }
}

